"""kewal thing

Revision ID: d7194f5f9a3e
Revises: ffdc0a98111c
Create Date: 2021-08-16 10:56:30.296607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7194f5f9a3e'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choreTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bunnyId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('choreId', sa.Integer(), nullable=True),
    sa.Column('bunnyComplete', sa.Boolean(), nullable=True),
    sa.Column('userComplete', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bunnyId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['choreId'], ['choreTypes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('choreId', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['choreId'], ['choreTypes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('isBunny', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=250), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'address')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'isBunny')
    op.drop_column('users', 'name')
    op.drop_table('pricings')
    op.drop_table('chores')
    op.drop_table('choreTypes')
    # ### end Alembic commands ###
