// import React from 'react';
import {useEffect} from 'react';
import { useSelector, useDispatch} from 'react-redux';
import { Link } from 'react-router-dom';
import {getChoreTypes} from '../../store/choreType.js';
import './homepage.css'


function Home() {
//bring in choretypes
  const dispatch = useDispatch();
  const choreTypes = useSelector(state => {
    return Object.values(state.choreType);
  });

  useEffect(() => {
    dispatch(getChoreTypes());
  }, [dispatch]);

  if(!choreTypes) {
    return <div>Loading...</div>;
  }


  return (
    <>
      <h1>Home</h1>
      <div className="categoriesContainer">


        <div className="cat1 catBox">
          <h2>cat</h2>
             <ul>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
             </ul>
        </div>

        <div className="cat2 catBox">
          <h2>cat</h2>
          <ul>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
             </ul>
        </div>

        <div className="cat3 catBox">
          <h2>cat</h2>
          <ul>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
             </ul>
        </div>

        <div className="cat4 catBox">
          <h2>cat</h2>
          <ul>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
             </ul>
        </div>

        <div className="cat5 catBox">
          <h2>cat</h2>
          <ul>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
             </ul>
        </div>

        <div className="cat6 catBox">
          <h2>cat</h2>
          <ul>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
             </ul>
        </div>

        <div className="cat7 catBox">
          <h2>cat</h2>
          <ul>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
             </ul>
        </div>

        <div className="cat8 catBox">
          <h2>cat</h2>
          <ul>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
                            <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
              <li>
                ok
              </li>
                            <li>
                ok
              </li>
             </ul>
        </div>









      </div>
    </>
  );
}
export default Home;
